In [1]:
import torch as th

c:\Users\eszna\miniconda3\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [3]:
INPUT_NUM_FRAMES = 8
INPUT_NUM_SHOTS = 16
INPUT_NUM_SAMPLES = 513

In [7]:
tensor = th.randn(INPUT_NUM_FRAMES, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)
print(tensor.shape)
print(tensor)

torch.Size([8, 16, 513])
tensor([[[ 0.3035,  0.0546, -1.8916,  ...,  0.0229, -0.8479, -0.2714],
         [-0.0520,  0.9667,  1.6239,  ...,  1.1671,  0.2802,  0.2478],
         [ 1.2496,  0.8742,  1.5610,  ...,  0.2361, -0.2178, -0.5147],
         ...,
         [-0.3502, -1.5130, -1.0031,  ..., -0.8323,  0.5058,  0.0280],
         [-0.8373,  0.2329,  0.6382,  ..., -0.6497, -1.2095, -0.0677],
         [ 1.1621, -2.0406, -0.7588,  ..., -0.3055,  1.8073,  0.7462]],

        [[-0.0577,  1.9125,  0.1380,  ..., -0.5996,  0.4904, -0.7886],
         [-0.5222, -0.3170,  1.1275,  ..., -0.3599, -0.6733,  0.5488],
         [ 0.1797,  0.9448,  1.3894,  ...,  0.0269, -1.3711, -0.8472],
         ...,
         [ 0.6028, -1.6825, -0.1903,  ...,  0.5838, -0.7490, -0.9237],
         [ 0.4963,  0.6166, -1.5584,  ...,  0.8379, -0.6498,  0.5276],
         [ 0.2459, -0.9257,  0.5477,  ...,  0.3721,  0.5308,  0.3349]],

        [[-1.4432, -0.7390, -1.0185,  ..., -1.2737, -1.5779,  0.4508],
         [-0.2570, -

In [14]:
src = th.rand(INPUT_NUM_FRAMES, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)
target = th.rand(INPUT_NUM_FRAMES, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)
tranformer = th.nn.Transformer(d_model=INPUT_NUM_SAMPLES, nhead=3, num_encoder_layers=6)
output = tranformer(src, target)
print(output.shape)
print(output)

c:\Users\eszna\miniconda3\Lib\site-packages\torch\nn\modules\transformer.py:307: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")


torch.Size([8, 16, 513])
tensor([[[-1.3249, -0.6562, -0.9328,  ..., -1.0165, -0.9106, -0.3370],
         [-1.3910,  0.4849, -1.3068,  ..., -1.3775, -0.7459, -0.0086],
         [-1.1262, -0.0726, -0.9685,  ..., -1.6376, -1.2930,  0.0669],
         ...,
         [-1.4456, -0.4105, -1.1261,  ..., -1.6567, -0.5363,  0.8601],
         [-0.9522, -0.3815, -0.9671,  ..., -2.9072,  1.0063,  0.8751],
         [-0.5490, -0.7015, -0.1915,  ..., -1.7616, -1.4931,  0.6862]],

        [[-0.8090, -1.1492,  0.3075,  ..., -1.3865, -0.8674,  0.5745],
         [-0.8424, -0.6660, -0.1465,  ..., -0.9639, -0.3047, -0.1680],
         [-1.2764, -0.1589, -1.2321,  ..., -2.4243, -0.5671, -0.4900],
         ...,
         [-0.8678, -0.5011, -0.8002,  ..., -1.8278, -0.4234,  0.1781],
         [-0.0087, -1.2541, -0.9698,  ..., -2.2691, -0.7363,  1.1366],
         [-0.6734, -0.7599, -0.5021,  ..., -1.2946, -0.8837,  0.4195]],

        [[-0.9761, -1.5037, -1.5354,  ..., -1.4493,  0.1945,  0.1282],
         [-1.0821, -

In [18]:
conv_layer = th.nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=1)

# Reshape the input tensor to match the expected input shape of Conv2d
# Conv2d expects input of shape (batch_size, channels, height, width)
# Here, we treat INPUT_NUM_FRAMES as batch_size
reshaped_tensor = src.view(INPUT_NUM_FRAMES, 1, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)

# Apply the convolutional layer
conv_output = conv_layer(reshaped_tensor)
print(conv_output.shape)
print(conv_output)

torch.Size([8, 1, 16, 513])
tensor([[[[ 0.1607,  0.2079,  0.2222,  ...,  0.3945,  0.3787,  0.1123],
          [ 0.1547,  0.3448,  0.3480,  ...,  0.3785,  0.3459,  0.0743],
          [ 0.1397,  0.3786,  0.3024,  ...,  0.4181,  0.3964,  0.0537],
          ...,
          [ 0.1411,  0.3779,  0.1557,  ...,  0.5615,  0.2502,  0.1039],
          [ 0.0812,  0.4870,  0.1891,  ...,  0.7161,  0.2516,  0.1618],
          [ 0.0300,  0.2879,  0.1963,  ...,  0.5446,  0.0831,  0.1472]]],


        [[[ 0.0634,  0.4059,  0.4069,  ...,  0.4795,  0.2878,  0.2010],
          [ 0.2176,  0.2998,  0.4785,  ...,  0.5356,  0.3734,  0.0880],
          [ 0.1864,  0.4003,  0.5657,  ...,  0.4279,  0.5544,  0.0812],
          ...,
          [ 0.0837,  0.4768,  0.2333,  ...,  0.1843,  0.3935,  0.1964],
          [ 0.0873,  0.2206,  0.4172,  ...,  0.4285,  0.2741,  0.2106],
          [ 0.1147,  0.0693,  0.2864,  ...,  0.5617,  0.1415,  0.0370]]],


        [[[ 0.0654,  0.4711,  0.1993,  ...,  0.3724,  0.3940,  0.1563]

In [20]:
#Full Flow
# Reshape the input tensor to match the expected input shape of Conv2d
# Conv2d expects input of shape (batch_size, channels, height, width)
# Here, we treat INPUT_NUM_FRAMES as batch_size
reshaped_tensor = src.view(INPUT_NUM_FRAMES, 1, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)

# Apply the convolutional layer
conv_output = conv_layer(reshaped_tensor)
print(conv_output.shape)

# Reshape the output tensor to match the expected input shape of Transformer
# Transformer expects input of shape (sequence_length, batch_size, d_model)
# Here, we treat INPUT_NUM_SHOTS as sequence_length and INPUT_NUM_SAMPLES as d_model
reshaped_tensor = conv_output.view(INPUT_NUM_FRAMES, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)    
print(reshaped_tensor.shape)

# Apply the transformer
output = tranformer(reshaped_tensor, reshaped_tensor)
print(output.shape)

print(output)

torch.Size([8, 1, 16, 513])
torch.Size([8, 16, 513])
torch.Size([8, 16, 513])
tensor([[[-0.9797, -0.1126, -0.2714,  ..., -1.5197, -0.4563, -0.3178],
         [-1.2209, -0.1903, -1.0866,  ..., -2.2133, -1.3801,  0.6142],
         [-0.7903, -0.1430, -1.1058,  ..., -2.1902, -0.7885, -0.0133],
         ...,
         [-1.2281, -0.6090, -1.3023,  ..., -2.0308, -0.4505,  0.7915],
         [-0.9986, -1.6100, -1.1983,  ..., -1.4816, -1.1801,  0.2326],
         [-0.3887,  0.2142, -1.6310,  ..., -1.5029, -1.0836,  0.1423]],

        [[-1.3195,  0.0901, -1.0481,  ..., -2.2466, -0.9455, -0.0872],
         [-0.1212, -0.0580, -0.7166,  ..., -1.8695,  0.1749, -0.1129],
         [-0.0470, -0.7651, -0.8520,  ..., -1.6547, -0.5619,  0.1654],
         ...,
         [-0.9004, -0.1400, -1.2482,  ..., -1.3382, -0.6251,  0.2723],
         [-0.5011, -1.0410, -0.7135,  ..., -1.8507, -1.0604,  0.8196],
         [-0.8209, -0.2629, -1.1446,  ..., -2.6196,  0.0800,  0.3325]],

        [[-0.8772, -0.9886, -0.6920,  