In [1]:
import torch as th

In [2]:
INPUT_NUM_FRAMES = 8
INPUT_NUM_SHOTS = 16
INPUT_NUM_SAMPLES = 513

In [3]:
tensor = th.randn(INPUT_NUM_FRAMES, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)
print(tensor.shape)
print(tensor)

torch.Size([8, 16, 513])
tensor([[[ 1.0697,  0.2883,  1.6725,  ...,  1.2902,  0.5838,  0.3887],
         [ 0.2202,  1.3064,  0.5272,  ..., -0.4052, -0.1754, -0.4436],
         [ 0.4609,  0.9690,  1.0313,  ..., -0.0095, -1.4749,  0.1886],
         ...,
         [-0.5537, -1.1102, -0.6680,  ...,  0.9722, -0.4078, -0.1424],
         [-1.7581,  0.9624,  0.8037,  ...,  0.6051,  0.3907, -1.3744],
         [ 1.7978, -0.1625, -0.0728,  ..., -1.4555,  0.2482,  1.4557]],

        [[-0.4664,  0.3054, -0.3222,  ..., -0.2710, -1.4407,  0.3710],
         [-0.1934,  0.5433,  1.0452,  ...,  0.0475, -0.3893,  1.4970],
         [-0.5600, -0.8551,  1.9716,  ..., -1.3721,  0.4243, -0.4418],
         ...,
         [ 1.0912, -0.5216,  0.0585,  ...,  0.1243, -0.9368, -0.4834],
         [-0.1158, -0.6875,  0.5857,  ..., -2.4228, -2.1988, -1.0237],
         [-1.0588,  1.7509, -0.6719,  ..., -0.2302,  0.4094,  0.8756]],

        [[-0.2417,  0.6076,  0.3813,  ..., -1.4281, -0.4077,  0.7200],
         [-0.2546,  

In [4]:
src = th.rand(INPUT_NUM_FRAMES, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)
target = th.rand(INPUT_NUM_FRAMES, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)
tranformer = th.nn.Transformer(d_model=INPUT_NUM_SAMPLES, nhead=3, num_encoder_layers=6)
output = tranformer(src, target)
print(output.shape)
print(output)

C:\Users\User\AppData\Local\Programs\Python\Python310\Lib\site-packages\torch\nn\modules\transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(


torch.Size([8, 16, 513])
tensor([[[-0.2749, -1.5319,  0.6602,  ...,  0.7589, -0.1699,  0.5049],
         [-1.1090, -0.7957,  0.3033,  ..., -0.8509,  0.1895,  0.9395],
         [-0.6180, -1.4549,  0.6048,  ...,  0.0263,  1.4170,  0.9824],
         ...,
         [ 0.0335, -1.2267, -0.8207,  ...,  1.1133,  0.2820,  1.8548],
         [-1.2482, -0.3012, -0.2607,  ..., -1.1113,  1.0808,  1.4458],
         [-0.4446, -0.6041, -0.7162,  ..., -0.8294, -1.3239,  1.3870]],

        [[ 1.4016, -2.6635, -0.5105,  ..., -0.3638, -0.3036,  0.8026],
         [-0.7903, -0.9168, -0.1070,  ..., -0.3223,  0.3682,  2.0032],
         [-1.4407, -1.0797,  0.1984,  ..., -0.1770,  0.3879,  0.5388],
         ...,
         [-0.9986, -0.1596, -0.1205,  ...,  0.2285, -0.3145,  1.1340],
         [-0.7085, -0.5514, -0.9320,  ..., -0.6109,  0.6219,  0.7748],
         [-0.6114, -1.0385, -1.1797,  ..., -0.5507,  0.2498,  0.5992]],

        [[-0.2412, -1.3015, -0.0860,  ...,  0.1960, -0.0650,  1.3396],
         [ 0.1255, -

In [6]:
conv_layer = th.nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=1)

# Reshape the input tensor to match the expected input shape of Conv2d
# Conv2d expects input of shape (batch_size, channels, height, width)
# Here, we treat INPUT_NUM_FRAMES as batch_size
reshaped_tensor = src.view(INPUT_NUM_FRAMES, 1, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)

# Apply the convolutional layer
conv_output = conv_layer(reshaped_tensor)
print(conv_output.shape)
print(conv_output)

torch.Size([8, 1, 16, 513])
tensor([[[[ 1.7223e-01,  3.3111e-01,  1.6417e-01,  ..., -1.1748e-01,
            3.6619e-01,  4.2179e-03],
          [ 3.1119e-01,  3.6069e-01, -1.6435e-02,  ...,  1.5901e-01,
            3.9913e-01,  2.8942e-01],
          [ 4.8629e-01,  1.6831e-01,  3.3891e-01,  ...,  2.6586e-01,
            7.4845e-02,  3.1926e-01],
          ...,
          [ 3.1736e-01,  3.5617e-01,  1.8920e-01,  ...,  3.7205e-01,
            3.6132e-01,  3.9979e-01],
          [ 4.6121e-01, -2.5154e-02,  4.4649e-01,  ...,  4.9748e-02,
            3.7322e-01,  1.4345e-01],
          [ 3.4014e-01, -8.4815e-02,  2.3315e-01,  ..., -6.1690e-02,
            2.0942e-01,  1.8454e-01]]],


        [[[ 8.7615e-02,  1.7760e-01,  3.1913e-03,  ...,  2.2826e-01,
            6.3584e-02,  2.0334e-01],
          [ 3.8730e-01,  2.3870e-01,  3.2886e-01,  ...,  1.0628e-01,
            5.2251e-01,  1.9734e-01],
          [ 1.2287e-01,  1.3198e-01,  5.2217e-01,  ...,  2.8285e-01,
            2.5804e-01,  3.0

In [8]:
#Full Flow
# Reshape the input tensor to match the expected input shape of Conv2d
# Conv2d expects input of shape (batch_size, channels, height, width)
# Here, we treat INPUT_NUM_FRAMES as batch_size
reshaped_tensor = src.view(INPUT_NUM_FRAMES, 1, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)

# Apply the convolutional layer
conv_output = conv_layer(reshaped_tensor)
#print(conv_output.shape)

# Reshape the output tensor to match the expected input shape of Transformer
# Transformer expects input of shape (sequence_length, batch_size, d_model)
# Here, we treat INPUT_NUM_SHOTS as sequence_length and INPUT_NUM_SAMPLES as d_model
reshaped_tensor = conv_output.view(INPUT_NUM_FRAMES, INPUT_NUM_SHOTS, INPUT_NUM_SAMPLES)    
print(reshaped_tensor.shape)

# Apply the transformer
output = tranformer(reshaped_tensor, reshaped_tensor)
#print(output.shape)

#print(output)

torch.Size([8, 16, 513])
